# Generated by Django 3.2.2 on 2021-05-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_dislikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='country',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
