# Generated by Django 3.2.2 on 2021-05-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='grades',
            field=models.CharField(default='1', max_length=255),
        ),
    ]
